# Generated by Django 5.0.4 on 2026-07-08 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Caja pizzería',
                'verbose_name_plural': 'Cajas pizzería',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComboPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('por_cobrar', 'Por cobrar')], default='libre', max_length=20)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('forma', models.CharField(choices=[('redonda', 'Redonda'), ('cuadrada', 'Cuadrada')], default='cuadrada', max_length=10)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ProductoSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('alitas', 'Alitas'), ('hamburguesa', 'Hamburguesa'), ('para_picar', 'Para picar'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto simple',
                'verbose_name_plural': 'Productos simples',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pizza', 'Pizza'), ('alitas', 'Alitas')], max_length=10)),
                ('es_premium', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
                'ordering': ['tipo', '-es_premium', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TamanoPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recargo_premium_completo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recargo_premium_mitad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tamaño de pizza',
                'verbose_name_plural': 'Tamaños de pizza',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CajaPizzeriaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_efectivo', to='pizzeria.cajapizzeria')),
            ],
            options={
                'verbose_name': 'Caja pizzería - Efectivo',
                'verbose_name_plural': 'Cajas pizzería - Efectivo',
            },
        ),
        migrations.CreateModel(
            name='CajaPizzeriaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_transferencia', to='pizzeria.cajapizzeria')),
            ],
            options={
                'verbose_name': 'Caja pizzería - Transferencia',
                'verbose_name_plural': 'Cajas pizzería - Transferencia',
            },
        ),
        migrations.CreateModel(
            name='ComboComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('papas', 'Papas'), ('alitas', 'Alitas'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('helado', 'Helado')], max_length=15)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('detalle', models.CharField(blank=True, max_length=100)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='pizzeria.combopizzeria')),
            ],
            options={
                'verbose_name': 'Componente de combo',
                'verbose_name_plural': 'Componentes de combo',
            },
        ),
        migrations.CreateModel(
            name='GastoPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='pizzeria.cajapizzeria')),
            ],
            options={
                'verbose_name': 'Gasto pizzería',
                'verbose_name_plural': 'Gastos pizzería',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mesa', 'En mesa'), ('llevar', 'Para llevar')], max_length=10)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('por_cobrar', 'Por cobrar'), ('cobrado', 'Cobrado'), ('anulado', 'Anulado')], default='abierto', max_length=20)),
                ('forma_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_dia', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizzeria.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_pizzeria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de pizzería',
                'verbose_name_plural': 'Pedidos de pizzería',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProductoSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_simples', to='pizzeria.pedidopizzeria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzeria.productosimple')),
            ],
            options={
                'verbose_name': 'Producto simple de pedido',
                'verbose_name_plural': 'Productos simples de pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizzeria.pedidopizzeria')),
                ('sabor_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
                ('sabor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzeria.tamanopizza')),
            ],
            options={
                'verbose_name': 'Pizza de pedido',
                'verbose_name_plural': 'Pizzas de pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzeria.combopizzeria')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='pizzeria.pedidopizzeria')),
                ('sabor_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
                ('sabor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzeria.tamanopizza')),
            ],
            options={
                'verbose_name': 'Combo de pedido',
                'verbose_name_plural': 'Combos de pedido',
            },
        ),
        migrations.CreateModel(
            name='ComboTamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanos', to='pizzeria.combopizzeria')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzeria.tamanopizza')),
            ],
            options={
                'verbose_name': 'Tamaño de combo',
                'verbose_name_plural': 'Tamaños de combo',
                'unique_together': {('combo', 'tamano')},
            },
        ),
    ]
