# Generated by Django 5.0.4 on 2026-07-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopizzeria',
            name='tipo',
            field=models.CharField(choices=[('mesa', 'En mesa'), ('llevar', 'Para llevar'), ('delivery', 'Domicilio')], max_length=10),
        ),
    ]
