# Generated by Django 5.0.4 on 2026-07-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_alter_pedidopizzeria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopizzeria',
            name='valor_moto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
