# Generated by Django 5.0.4 on 2026-07-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_pedidocombosaboralitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProductoSimpleSaborAlitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores_alitas', to='pizzeria.pedidoproductosimple')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
            ],
            options={
                'verbose_name': 'Sabor de alitas de producto',
                'verbose_name_plural': 'Sabores de alitas de producto',
            },
        ),
    ]
