# Generated by Django 5.0.4 on 2026-07-23 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_pedidoproductosimplesaboralitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('cocinando', 'Cocinando'), ('listo', 'Listo'), ('completo', 'Completo')], default='en_proceso', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_preparacion', to='pizzeria.pedidopizzeria')),
            ],
            options={
                'verbose_name': 'Ítem de preparación',
                'verbose_name_plural': 'Ítems de preparación',
                'ordering': ['id'],
            },
        ),
    ]
