# Generated by Django 5.0.4 on 2026-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0006_itempreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempreparacion',
            name='grupo',
            field=models.CharField(blank=True, default='', help_text='Nombre del combo al que pertenece este ítem (ej: "Mega Combo 1"), vacío si es un ítem suelto.', max_length=200),
        ),
    ]
