# Generated by Django 5.0.4 on 2026-07-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_itempreparacion_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempreparacion',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_preparacion', to='pizzeria.pedidocombo'),
        ),
        migrations.AddField(
            model_name='itempreparacion',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_preparacion', to='pizzeria.pedidopizza'),
        ),
        migrations.AddField(
            model_name='itempreparacion',
            name='producto_simple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_preparacion', to='pizzeria.pedidoproductosimple'),
        ),
    ]
