# Generated by Django 5.0.4 on 2026-07-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_itempreparacion_combo_itempreparacion_pizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocombo',
            name='sabor_bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor'),
        ),
        migrations.AddField(
            model_name='pedidoproductosimple',
            name='sabor_bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor'),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='tipo',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('alitas', 'Alitas'), ('bebida', 'Bebida')], max_length=10),
        ),
    ]
