# Generated by Django 5.0.4 on 2026-07-28 21:47

from django.db import migrations

SABORES_BEBIDA = ['Coca-Cola', 'Fanta', 'Sprite', 'Fioravanti', 'Inca Kola', 'Pepsi']


def crear_sabores_bebida(apps, schema_editor):
    Sabor = apps.get_model('pizzeria', 'Sabor')
    for nombre in SABORES_BEBIDA:
        Sabor.objects.get_or_create(nombre=nombre, tipo='bebida')


def eliminar_sabores_bebida(apps, schema_editor):
    Sabor = apps.get_model('pizzeria', 'Sabor')
    Sabor.objects.filter(tipo='bebida', nombre__in=SABORES_BEBIDA).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0009_pedidocombo_sabor_bebida_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_sabores_bebida, eliminar_sabores_bebida),
    ]
