# Generated by Django 5.0.4 on 2026-07-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0010_seed_sabores_bebida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocombo',
            name='sabor_bebida',
        ),
        migrations.AddField(
            model_name='combopizzeria',
            name='pizza_tamano_fijo',
            field=models.ForeignKey(blank=True, help_text='Tamaño predeterminado (no seleccionable) de la pizza completa de este combo, ej. "Pizza Familiar" en un combo de precio fijo. Vacío si el combo no incluye pizza completa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.tamanopizza'),
        ),
        migrations.AddField(
            model_name='combopizzeria',
            name='precio_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio único del combo cuando no tiene tamaños (ComboTamano). Si el combo sí tiene tamaños, el precio se calcula por tamaño y este campo se ignora.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='combocomponente',
            name='tipo',
            field=models.CharField(choices=[('papas', 'Papas'), ('alitas', 'Alitas'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('helado', 'Helado'), ('hamburguesa', 'Hamburguesa'), ('michelada', 'Michelada'), ('porcion_pizza', 'Porción de pizza')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pedidocombo',
            name='sabor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor'),
        ),
        migrations.AlterField(
            model_name='pedidocombo',
            name='tamano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizzeria.tamanopizza'),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='tipo',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('alitas', 'Alitas'), ('bebida', 'Bebida'), ('michelada', 'Michelada')], max_length=10),
        ),
        migrations.CreateModel(
            name='PedidoComboSaborBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores_bebida', to='pizzeria.pedidocombo')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
            ],
            options={
                'verbose_name': 'Sabor de bebida de combo',
                'verbose_name_plural': 'Sabores de bebida de combo',
            },
        ),
        migrations.CreateModel(
            name='PedidoComboSaborMichelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores_michelada', to='pizzeria.pedidocombo')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
            ],
            options={
                'verbose_name': 'Sabor de michelada de combo',
                'verbose_name_plural': 'Sabores de michelada de combo',
            },
        ),
        migrations.CreateModel(
            name='PedidoComboSaborPorcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores_porcion', to='pizzeria.pedidocombo')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor')),
            ],
            options={
                'verbose_name': 'Sabor de porción de combo',
                'verbose_name_plural': 'Sabores de porción de combo',
            },
        ),
    ]
