# Generated by Django 5.0.4 on 2026-07-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0013_set_descripcion_combos_extendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopizzeria',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='CajaPizzeriaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_tarjeta', to='pizzeria.cajapizzeria')),
            ],
            options={
                'verbose_name': 'Caja pizzería - Tarjeta',
                'verbose_name_plural': 'Cajas pizzería - Tarjeta',
            },
        ),
        migrations.CreateModel(
            name='PersonaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_cobro', to='pizzeria.pedidopizzeria')),
            ],
            options={
                'verbose_name': 'Persona de cobro',
                'verbose_name_plural': 'Personas de cobro',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pizzeria.pedidopizzeria')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pizzeria.personacobro')),
            ],
            options={
                'verbose_name': 'Pago de pedido',
                'verbose_name_plural': 'Pagos de pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionItemCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cobro', to='pizzeria.pedidocombo')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cobro', to='pizzeria.pedidopizza')),
                ('producto_simple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cobro', to='pizzeria.pedidoproductosimple')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pizzeria.personacobro')),
            ],
            options={
                'verbose_name': 'Asignación de ítem a persona',
                'verbose_name_plural': 'Asignaciones de ítems a personas',
            },
        ),
    ]
