# Generated by Django 5.0.4 on 2026-08-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0016_fix_mesa_legacy_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
