# Generated by Django 5.0.4 on 2026-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0017_mesa_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('por_cobrar', 'Por cobrar')], default='libre', max_length=20),
        ),
    ]
