# Generated by Django 5.0.4 on 2026-09-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0018_alter_mesa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopizzeria',
            name='pago_delivery',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], help_text='Cómo se cobra un pedido a domicilio: en efectivo (lo cobra el motorizado al cliente) o ya transferido (el motorizado no cobra nada al entregar).', max_length=15, null=True),
        ),
    ]
