# Generated by Django 5.0.4 on 2026-09-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0019_pedidopizzeria_pago_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopizzeria',
            name='personas',
            field=models.PositiveIntegerField(blank=True, help_text='Comensales en la mesa. Precarga la cantidad de personas al dividir la cuenta.', null=True),
        ),
    ]
