# Generated by Django 5.0.4 on 2026-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0020_pedidopizzeria_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocombosaborbebida',
            name='temperatura',
            field=models.CharField(blank=True, choices=[('helada', 'Helada'), ('ambiente', 'Al ambiente')], max_length=10),
        ),
    ]
