# Generated by Django 5.0.4 on 2026-09-10 05:15

from django.db import migrations, models


# Las zonas eran texto libre. Se mapean a las dos categorías nuevas antes de
# apretar el campo; lo que no reconocemos cae en 'dentro', que es el default.
EQUIVALENCIAS = {
    'interior': 'dentro',
    'dentro': 'dentro',
    'salon': 'dentro',
    'salón': 'dentro',
    'exterior': 'afuera',
    'afuera': 'afuera',
    'patio': 'afuera',
    'terraza': 'afuera',
    'jardin': 'afuera',
    'jardín': 'afuera',
}


def normalizar_zonas(apps, schema_editor):
    Mesa = apps.get_model('pizzeria', 'Mesa')
    for mesa in Mesa.objects.all():
        actual = (mesa.zona or '').strip().lower()
        nueva = EQUIVALENCIAS.get(actual, 'dentro')
        if mesa.zona != nueva:
            mesa.zona = nueva
            mesa.save(update_fields=['zona'])


def revertir_zonas(apps, schema_editor):
    Mesa = apps.get_model('pizzeria', 'Mesa')
    Mesa.objects.filter(zona='dentro').update(zona='Interior')
    Mesa.objects.filter(zona='afuera').update(zona='Exterior')


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0021_pedidocombosaborbebida_temperatura'),
    ]

    operations = [
        migrations.RunPython(normalizar_zonas, revertir_zonas),
        migrations.AlterField(
            model_name='mesa',
            name='zona',
            field=models.CharField(choices=[('dentro', 'Dentro'), ('afuera', 'Afuera')], default='dentro', max_length=10),
        ),
    ]
