# Generated by Django 5.0.4 on 2026-09-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0022_alter_mesa_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproductosimple',
            name='temperatura',
            field=models.CharField(blank=True, choices=[('helada', 'Helada'), ('ambiente', 'Al ambiente')], max_length=10),
        ),
    ]
