# Generated by Django 5.0.4 on 2026-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0023_pedidoproductosimple_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='reserva_hora',
            field=models.DateTimeField(blank=True, help_text='A qué hora llega la reserva. Solo tiene sentido mientras la mesa está reservada.', null=True),
        ),
    ]
