# Generated by Django 5.0.4 on 2026-09-11 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0024_mesa_reserva_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajapizzeria',
            name='abierta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_pizzeria_abiertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cajapizzeria',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_pizzeria_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovimientoCajaPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retiro', 'Retiro a bóveda'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(blank=True, choices=[('insumos', 'Insumos'), ('transporte', 'Transporte'), ('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('conteo', models.JSONField(blank=True, help_text='Retiros: cantidad por denominación.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, help_text='Lo que debía quedar en el cajón justo después; se guarda al registrar, no se recalcula.', max_digits=10)),
                ('anulado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pizzeria.cajapizzeria')),
            ],
            options={
                'verbose_name': 'Movimiento de caja pizzería',
                'verbose_name_plural': 'Movimientos de caja pizzería',
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
