# Generated by Django 5.0.4 on 2026-09-13 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0027_quitar_por_cobrar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajapizzeria',
            name='conteo_cierre',
            field=models.JSONField(blank=True, help_text='Arqueo final: cantidad por denominación.', null=True),
        ),
        migrations.AddField(
            model_name='movimientocajapizzeria',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocajapizzeria',
            name='anulado_motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimientocajapizzeria',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
