# Generated by Django 5.0.4 on 2026-09-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0029_bebidas_combo_con_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopizzeria',
            name='pagado_adelantado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se cobró por adelantado. La orden sigue abierta (mesa ocupada, cocina en curso) hasta que se cierra con todo servido; entonces pasa a cobrado.', null=True),
        ),
    ]
