# Generated by Django 5.0.4 on 2026-09-15 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0030_pedido_pagado_adelantado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopizzeria',
            name='cobrado_por',
            field=models.ForeignKey(blank=True, help_text='Quién registró el cobro. Vacío en órdenes cobradas antes de guardarse este dato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidopizzeria',
            name='recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo que entregó el cliente (cobro simple en efectivo); de ahí sale el cambio.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CambioMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(help_text='Efectivo, Tarjeta, Transferencia o Mixto', max_length=15)),
                ('a', models.CharField(max_length=15)),
                ('motivo', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_metodo', to='pizzeria.pedidopizzeria')),
            ],
            options={
                'verbose_name': 'Cambio de método de pago',
                'verbose_name_plural': 'Cambios de método de pago',
                'ordering': ['-creado_en'],
            },
        ),
    ]
