# Generated by Django 5.0.4 on 2026-09-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0033_productosimple_categoria_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='combopizzeria',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Botón del menú donde aparece. Vacío = "Combos".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='pizzeria.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='combopizzeria',
            name='pizzas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 pizza'), (2, '2 pizzas')], default=1, help_text='Pizzas completas que trae el combo (2 en los 2x1). Cada una lleva su sabor o mitad y mitad y paga su propio recargo premium. Solo cuenta si el combo tiene pizza.'),
        ),
        migrations.AddField(
            model_name='pedidocombo',
            name='pizza2_sabor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor'),
        ),
        migrations.AddField(
            model_name='pedidocombo',
            name='pizza2_sabor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pizzeria.sabor'),
        ),
    ]
