# Generated by Django 5.0.4 on 2026-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0035_seed_martes_2x1'),
    ]

    operations = [
        migrations.AddField(
            model_name='combopizzeria',
            name='recargo_cajas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si tiene valor, al tomar el pedido aparece la casilla "Recargo por cajas" y suma este monto por combo. Vacío = el combo no ofrece la casilla.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedidocombo',
            name='con_cajas',
            field=models.BooleanField(default=False, help_text='Se cobró el recargo por cajas (ya incluido en el precio unitario).'),
        ),
    ]
