# Generated by Django 5.2 on 2025-05-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sopa', 'Sopa'), ('almuerzo', 'Almuerzo'), ('jugo', 'Jugo'), ('postre', 'Postre'), ('extra', 'Extra')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDiaSopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sopas', to='menu.menudia')),
                ('sopa', models.ForeignKey(limit_choices_to={'tipo': 'sopa'}, on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDiaSegundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundos', to='menu.menudia')),
                ('segundo', models.ForeignKey(limit_choices_to={'tipo': 'segundo'}, on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDiaJugo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugos', to='menu.menudia')),
                ('jugo', models.ForeignKey(limit_choices_to={'tipo': 'jugo'}, on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDiaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='menu.menudia')),
                ('extra', models.ForeignKey(limit_choices_to={'tipo': 'extra'}, on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
        ),
        migrations.AddField(
            model_name='menudia',
            name='postre',
            field=models.ForeignKey(limit_choices_to={'tipo': 'postre'}, on_delete=django.db.models.deletion.CASCADE, related_name='menus_postre', to='menu.plato'),
        ),
    ]
