# Generated by Django 5.2 on 2025-05-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('sopa', 'Sopa'), ('segundo', 'Segundo'), ('almuerzo', 'Almuerzo'), ('jugo', 'Jugo'), ('postre', 'Postre'), ('extra', 'Extra')], max_length=100),
        ),
    ]
