# Generated by Django 5.2 on 2025-05-21 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_plato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudia',
            name='postre',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'postre'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_postre', to='menu.plato'),
        ),
    ]
