# Generated by Django 5.2 on 2025-05-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menudia_postre'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudiasegundo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menudiasopa',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
