# Generated by Django 5.2 on 2025-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menudiasegundo_cantidad_menudiasopa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sopa', 'Sopa'), ('segundo', 'Segundo'), ('almuerzo', 'Almuerzo'), ('jugo', 'Jugo'), ('postre', 'Postre'), ('extra', 'Extra')], max_length=100, unique=True)),
                ('precio_servirse', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_llevar', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='precio_porcion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='precio_servirse',
            field=models.DecimalField(decimal_places=2, default=3.25, max_digits=6),
            preserve_default=False,
        ),
    ]
