# Generated by Django 5.2 on 2025-06-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_precio_plato_precio_porcion_plato_precio_servirse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='precio_porcion',
            new_name='precio_llevar',
        ),
    ]
