# Generated by Django 5.2 on 2025-06-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_precio_porcion_plato_precio_llevar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(choices=[('sopa', 'Sopa'), ('segundo', 'Segundo'), ('almuerzo', 'Almuerzo'), ('jugo', 'Jugo'), ('postre', 'Postre'), ('extra', 'Extra')], max_length=100, unique=True)),
                ('precio_servirse', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_llevar', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.RenameField(
            model_name='plato',
            old_name='nombre',
            new_name='nombre_plato',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='precio_llevar',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='precio_servirse',
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('sopa', 'Sopa'), ('segundo', 'Segundo'), ('jugo', 'Jugo'), ('postre', 'Postre'), ('extra', 'Extra')], max_length=100),
        ),
    ]
