# Generated by Django 5.0.4 on 2025-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_producto_delete_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudiasegundo',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menudiasopa',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
