# Generated by Django 5.2.6 on 2025-09-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_inicializar_cantidad_actual_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudiajugo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menudiajugo',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
