# Generated by Django 5.2.6 on 2025-09-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menudiajugo_cantidad_menudiajugo_cantidad_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudiajugo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='menudiajugo',
            name='cantidad_actual',
        ),
    ]
