# Generated by Django 5.2.6 on 2025-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_menudiajugo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
