# Generated by Django 5.0.4 on 2025-09-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Cajas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CajaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_efectivo', to='caja.cajadiaria')),
            ],
            options={
                'verbose_name': 'Caja Efectivo',
                'verbose_name_plural': 'Cajas Efectivo',
            },
        ),
        migrations.CreateModel(
            name='CajaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_transferencia', to='caja.cajadiaria')),
            ],
            options={
                'verbose_name': 'Caja Transferencia',
                'verbose_name_plural': 'Cajas Transferencia',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('caja_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='caja.cajadiaria')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
