# Generated by Django 5.2.6 on 2025-10-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadiaria',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cajaefectivo',
            name='caja_diaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_efectivo', to='caja.cajadiaria'),
        ),
        migrations.AlterField(
            model_name='cajatransferencia',
            name='caja_diaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_transferencia', to='caja.cajadiaria'),
        ),
    ]
