# Generated by Django 5.2 on 2025-06-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0005_precio_plato_precio_porcion_plato_precio_servirse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Servirse', 'Servirse'), ('Reservado', 'Reservado'), ('Levar', 'Levar')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero_mesa', models.IntegerField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('jugo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiajugo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almuerzos', to='pedidos.pedido')),
                ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiasegundo')),
                ('sopa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiasopa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSegundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('jugo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiajugo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundos', to='pedidos.pedido')),
                ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiasegundo')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('jugo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiajugo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sopas', to='pedidos.pedido')),
                ('sopa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menudiasopa')),
            ],
        ),
    ]
