# Generated by Django 5.2 on 2025-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferecncia', 'Transferecncia')], default='Efectivo', max_length=15),
        ),
    ]
