# Generated by Django 5.2 on 2025-06-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_forma_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_cliente',
            new_name='contacto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefono',
        ),
    ]
