# Generated by Django 5.2 on 2025-07-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_cajadiara'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CajaDiara',
            new_name='CajaDiaria',
        ),
    ]
