# Generated by Django 5.0.4 on 2025-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedidoalmuerzo_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=15),
        ),
    ]
