# Generated by Django 5.0.4 on 2025-08-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedidoalmuerzo_observacion_pedidosegundo_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subtipo_reservado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
