# Generated by Django 5.0.4 on 2025-08-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_subtipo_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Servirse', 'Servirse'), ('Reservado', 'Reservado'), ('Llevar', 'Llevar')], max_length=20),
        ),
    ]
