# Generated by Django 5.2 on 2025-09-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedido_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CajaDiaria',
        ),
    ]
