# Generated by Django 5.2.6 on 2025-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_delete_cajadiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=15),
        ),
    ]
