# Generated by Django 5.2.6 on 2025-10-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_pedido_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_dia',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
