# Generated by Django 5.2.6 on 2025-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_numero_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observaciones_generales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
