# Generated by Django 5.2.6 on 2025-10-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_plato_precio'),
        ('pedidos', '0016_pedido_observaciones_generales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.ForeignKey(limit_choices_to={'tipo': 'extra'}, on_delete=django.db.models.deletion.PROTECT, to='menu.plato')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='pedidos.pedido')),
            ],
        ),
    ]
