# Generated by Django 5.0.4 on 2026-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pedidoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='monto_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Mixto', 'Mixto')], default='Efectivo', max_length=15),
        ),
    ]
